
movies = ["waqt", 
"hulchul",
"ek vivah aisa bhi",
"dhoom",
"dabang",
"hum saath saath h",
"ek aur ek gyara",
"sonu ke titu ki sweety",
"sandwich",
"dilwale dulhania le jayenge",
'khoobsurat',
"aamdani aathani kharcha rupayaa",
'mother india',
'pk',
'mister india',
"man marziya",
"golmaal again",
"hum aapke hai kaun",
"luck",
"holiday",
"chhapak",
"chhichore",
"pati patni aur vo",
"sooryansham",
"fukrey",
"bala",
"kesari",
"gully boy",
"good newwz",
"jannat",
"kick",
"luka chuppi",
"bajrangi bhaijaan",
"sanju",
"padmaavat",
"tiger zinda hai",
"lagaan",
"zindagi na milegi doobara",
"sholay",
"mission mangal",
"tanaji"
]